name = "vitrio-start"
main = "src/server/workers.ts"
compatibility_date = "2026-02-16"

# If you use Workers + Assets, configure this. Otherwise deploy SSR only.
# [assets]
# directory = "dist/client"
